# Generated by Django 3.0.3 on 2021-06-29 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('stage', models.CharField(choices=[('initialize', 'INITIALIZE'), ('inprogress', 'INPROGRESS'), ('solved', 'SOLVED')], max_length=50)),
                ('status', models.CharField(choices=[('inprogress', 'INPROGRESS'), ('solved', 'SOLVED')], max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('complaint_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Customer')),
                ('complaint_handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint_related_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
            ],
        ),
    ]
