# Generated by Django 3.0.3 on 2021-07-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solution',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
