# Generated by Django 3.0.3 on 2021-06-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Business'),
        ),
    ]
